server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cloudmart_users}
    username: ${DB_USER:cloudmart}
    password: ${DB_PASSWORD:cloudmart}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:cloudmart-super-secret-signing-key-change-me-in-prod-0123456789}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
